# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad30dee87da53a7f336bdf1d216c2fdeff38044a7c4f61a4cb47f783cd2757875597bd84e9c9576c2ed4e6ee5753a5a5f9169c0782267c34a822eb3fba6dd93c

test:
  secret_key_base: 56f85f2ccc80442ce87f0f3f3690cb3629053b8312eb63d65b28f82e8a57b11654074fbaef5d0e82e704b493ef84cba6910a5f93af256c13c3e872064cdd2fd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
