# User class definition
# Manages User attributes, relations, and validations
# Includes many attributes generated by Devise authentication middleware
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  # # # # #
  # Generated by Devise Middleware

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ''
  field :encrypted_password, type: String, default: ''

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  #
  # # # # #

  # Attributes
  field :username, type: String
  field :display_name, type: String

  # Validations
  validates :email, presence: true, uniqueness: true, format: { with: /@/ }
  validates :username, presence: true, uniqueness: true, length: { minimum: 4, maximum: 24 }
  validates :display_name, presence: true, length: { minimum: 4, maximum: 24 }

  # Relations
  has_many :contact_methods, class_name: 'ContactMethod'
  has_many :share_profiles, class_name: 'User', inverse_of: :created_by
  has_and_belongs_to_many :linked_profiles, class_name: 'ShareProfile', inverse_of: :linked_users
  has_many :update_dispatches, class_name: 'UpdateDispatch'

end
